import './style.css';
import {parseGPX,routeStats,terrainElevation,pointAtDistance,validateTerrain,type Track,type TerrainData} from './core';
import {TrailScene} from './scene';
import { QUALITY, validateScenery, type Quality, type SceneryData, type DetailFeature, type Coordinate } from './detail';
import {readProject,importPhoto,download,exportViewer,fetchGsiTerrain,MAX_PROJECT_BYTES,type Photo,type Peak,type Project} from './io';
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`
<header><div class="brand"><svg viewBox="0 0 44 44" aria-hidden="true"><path d="m3 34 13-24 10 17 6-11 10 18Z" fill="#ccddb8"/><path d="m12 18 4-8 5 8" fill="#fff"/></svg><div><div class="wordmark">3D YAMA</div><small>TRAIL DIORAMA</small></div></div><div class="header-note">歩いた道を、もう一度。</div><div class="header-actions"><button class="top-btn" id="about">使い方</button><button class="top-btn" id="save">保存・書き出し ↗</button></div></header>
<main class="layout"><aside class="sidebar" id="sidebar"><section class="intro"><div class="eyebrow">A LITTLE WORLD, YOUR TRAIL.</div><h1>山旅を、<br>手のひらに。</h1><p>GPXと写真から、自分だけの山の記録。<br>実際の地形を回して、歩いて、振り返る。</p></section>
<section class="route-card"><div class="route-head"><div class="route-kicker" id="route-kind">FIELD NOTE · SUMA, KOBE</div><h2 id="route-name">須磨の、小さな縦走。</h2><div class="route-subtitle" id="route-subtitle">栂尾山 → 横尾山 → 馬の背 → 東山</div></div><div class="metrics"><div class="metric"><span>距離</span><b id="distance">—</b><small>km</small></div><div class="metric"><span>累積上り</span><b id="ascent">—</b><small>m</small></div><div class="metric"><span>最高標高</span><b id="highest">—</b><small>m</small></div><div class="metric"><span>写真</span><b id="photo-count">0</b><small>枚</small></div></div></section>
<section class="realism-card"><p class="section-label">CLOSER TO THE MOUNTAIN</p><h3>岩の稜線、森の奥へ。</h3><p>実DEMに、Blenderの樹木・岩と、地図・写真を参考にした階段を重ねます。</p><div class="focus-buttons"><button data-focus="bare_rock">◈ 馬の背</button><button data-focus="steps">▤ 階段</button><button data-focus="forest">♧ 森</button></div><p class="detail-caveat">地形は実標高1:1。木の位置・岩の細部・階段の寸法と段数は実測ではありません。</p><a id="feature-source" href="./data/provenance.json" target="_blank" rel="noreferrer">位置と表現の出典を見る ↗</a></section>
<section><p class="section-label">YOUR OWN ADVENTURE</p><div class="import-actions"><button class="primary" id="import-gpx">＋ GPXを読み込む</button><button class="secondary" id="open-project">保存した記録を開く</button><button class="text-btn" id="sample">須磨サンプルに戻る</button></div><p class="privacy"><strong>◉ ファイルは、このブラウザの中だけ。</strong><br>アップロード・アカウント登録なし。</p></section>
<section class="photo-section"><div class="photo-section-head"><p class="section-label">MOMENTS ON THE TRAIL</p><button class="text-btn" id="add-photo">＋ 写真</button></div><div class="photos" id="photos"><span class="empty-photos">下のスライダーで場所を選んで、<br>その地点に写真を残せます。</span></div></section>
<section class="tools"><details><summary>地形とデータ</summary><div class="details-body"><p>付属の実地形は須磨の一部です。範囲外のGPXは、地形JSONを追加するか、日本国内向けの地理院DEMを取得できます。</p><button class="secondary" id="import-terrain">地形JSONを読み込む</button><button class="secondary" id="load-gsi">地理院DEMを取得…</button><label>画質 <select id="quality-sidebar"><option value="standard" selected>標準</option><option value="high">精細 · Blender</option><option value="low">軽量</option></select></label><p>地形の縦横比は1:1。線の太さは見やすさのための表現で、実際の道幅ではありません。</p></div></details></section>
<footer class="sidebar-footer">表示確認用の概略ルートです。<br>登山のナビゲーションには使用しないでください。<br><a href="https://maps.gsi.go.jp/development/ichiran.html" target="_blank" rel="noreferrer">地理院タイルを加工</a> · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a><br><a href="https://github.com/codex-9990/3D-YAMA" target="_blank" rel="noreferrer">View source on GitHub ↗</a></footer></aside>
<section class="stage" aria-label="3D登山ルートビューアー"><div id="scene"></div><div class="viewbar" role="group" aria-label="表示モード"><button data-mode="orbit" class="active" aria-pressed="true">◈ ジオラマ</button><button data-mode="walk" aria-pressed="false">↟ 歩く</button><button data-mode="overhead" aria-pressed="false">▱ 真上</button></div><div class="stage-topright"><select class="quality" id="quality" aria-label="画質"><option value="standard" selected>標準</option><option value="high">精細 · Blender</option><option value="low">軽量</option></select><button class="icon-btn" id="reset" aria-label="表示をリセット" title="表示をリセット">↺</button><button class="icon-btn" id="capture" aria-label="画像を保存" title="画像を保存">↓</button></div><div class="scene-tag"><b id="terrain-label">SUMA · REAL TERRAIN</b><br><span id="terrain-meta">GSI DEM / ACTUAL SCALE 1:1</span></div><div class="detail-controls"><div class="quality-tabs" role="group" aria-label="描画品質"><button data-quality="low" aria-pressed="false">軽量</button><button data-quality="standard" class="active" aria-pressed="true">標準</button><button data-quality="high" aria-pressed="false">精細</button></div><label class="route-toggle"><input id="route-visible" type="checkbox" checked>ルート線</label><p id="detail-status" role="status">標準 · 遠景の樹冠と岩・階段</p></div><div class="compass" aria-hidden="true">N<i></i></div><div class="stage-help" id="stage-help">ドラッグで回転 · ホイールでズーム · 右ドラッグで移動</div><button class="mobile-panel-toggle" id="mobile-panel">GPX・写真を追加 ↓</button>
<div class="notice" role="status" id="notice" hidden><button class="close" aria-label="通知を閉じる" id="dismiss">×</button><span id="notice-text"></span></div>
<div class="out-of-coverage" id="coverage" hidden><div class="coverage-card"><div class="mini-mark">△</div><h2>この道の地形を、もう一枚。</h2><p>GPXを読み込みました。付属の須磨DEMの範囲外です。<br>地形JSONを読み込むか、地理院の実標高を取得すると、3D表示できます。</p><button class="primary" id="coverage-gsi">地理院DEMを取得…</button><button class="secondary" id="coverage-terrain">地形JSONを読み込む</button></div></div>
<div class="bottom-panel"><div class="timeline-top"><div class="journey-label">EXPLORE THE TRAIL<strong id="current-label">スタート地点</strong></div><div class="play-tools"><span class="progress-text" id="progress-text">0 / 0 m</span><select class="speed" id="speed" aria-label="再生速度"><option value="8">8×</option><option value="20" selected>20×</option><option value="60">60×</option></select><button class="play-btn" id="play" aria-label="ルートを再生">▶</button></div></div><div class="profile-wrap"><svg id="profile" viewBox="0 0 600 57" preserveAspectRatio="none" role="img" aria-label="ルートの標高グラフ"></svg><span id="profile-pointer"></span></div><input id="progress" type="range" min="0" max="1000" step="1" value="0" aria-label="ルート上の現在位置"><div class="profile-caption"><span id="profile-min">標高 — m</span><span id="profile-source">地形データから標高を表示</span><span id="profile-max">— m</span></div></div><div class="loading" id="loading"><div><span class="dot-pulse"></span>山の地形をひらいています…</div></div></section></main>
<input class="hidden-input" id="gpx-file" type="file" accept=".gpx,application/gpx+xml"><input class="hidden-input" id="project-file" type="file" accept=".json"><input class="hidden-input" id="terrain-file" type="file" accept=".json"><input class="hidden-input" id="photo-file" type="file" accept="image/jpeg,image/png,image/webp" multiple>
<dialog id="about-dialog"><h2>一歩ずつ、思い出の中へ。</h2><p>ジオラマをドラッグして山を回し、「歩く」でルート上の視点へ。下のスライダーや再生ボタンで道をたどれます。</p><ol><li>GPXファイル（10 MB・5万点以下、範囲25 km以内）を読み込む。</li><li>写真を置く場所をスライダーで選び、「＋ 写真」で追加。写真は最大20枚、1枚12 MB以下。EXIFの位置情報は読まず、長辺1,280 pxに縮小してメタデータを除去します。</li><li>プロジェクトJSONで保存。静的ZIPなら、同じビューアーを自分のサーバーで公開できます。</li></ol><p>ファイルを選ぶだけでは外部送信されません。地形の取得を明示的に実行した場合だけ、対象地域のタイル番号とIPアドレスが国土地理院に伝わります。登山の現況・通行可否は表しません。</p><button class="primary" data-close="about-dialog">山を見てみる</button></dialog>
<dialog id="export-dialog"><h2>この山旅を、持ち帰る。</h2><p>保存にはルートの座標と、追加した写真が含まれます。公開・共有する場合は、位置情報や写っている人を確認してください。</p><div class="import-actions"><button class="primary" id="save-project">プロジェクトJSONを保存</button><button class="secondary" id="save-viewer">ポータブル・ビューアー ZIP</button></div><p>ZIPを展開して静的サーバーで配信できます。HTMLのダブルクリックでは動きません。写真とGPXは保存ボタンを押さない限り、ページを閉じると消えます。</p><button class="text-btn" data-close="export-dialog">閉じる</button></dialog>
<dialog id="gsi-dialog"><h2>実際の標高を取得しますか？</h2><p>日本国内の対象地域のタイルを国土地理院（cyberjapandata.gsi.go.jp）から取得します。地域が分かるタイル番号とIPアドレスが同サービスに伝わります。GPXファイルや写真自体は送信しません。</p><p>標高のない海域等を含む範囲は表示できません。読み込みに失敗しても、現在の記録は残ります。</p><div class="dialog-buttons"><button class="secondary" data-close="gsi-dialog">キャンセル</button><button class="primary" id="confirm-gsi">取得する</button></div></dialog>
<dialog id="photo-dialog"><h2 class="photo-title" id="photo-title">写真</h2><img id="photo-view" alt="選択したルートの写真"><div class="dialog-buttons"><button class="secondary" id="remove-photo">この写真を外す</button><button class="primary" data-close="photo-dialog">閉じる</button></div></dialog>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)! as T;
let scene:TrailScene;let scenery:SceneryData|undefined;let quality:Quality='standard';let terrain:TerrainData;let track:Track;let photos:Photo[]=[];let peaks:Peak[]=[];let meters=0,total=0,playing=false,lastFrame=0,covered=true,loadVersion=0,dirty=false,selectedPhoto='';let controller:AbortController|undefined;let mode:'orbit'|'walk'|'overhead'='orbit';
function notify(message:string,error=false){$('notice-text').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=false;}
function stop(){playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','ルートを再生');}
function isCovered(t:Track,d:TerrainData){return t.segments.every(s=>s.every(p=>p.lat>=d.bounds.south&&p.lat<=d.bounds.north&&p.lon>=d.bounds.west&&p.lon<=d.bounds.east));}
function enriched(t:Track):Track{return {name:t.name,segments:t.segments.map(seg=>seg.map(p=>({...p,elevation:covered?terrainElevation(terrain,p.lat,p.lon):p.elevation}))) };}
function setPosition(value:number){meters=Math.max(0,Math.min(total,value));$('progress').setAttribute('max',String(Math.max(1,total)));($('progress') as HTMLInputElement).value=String(meters);$('progress-text').textContent=`${Math.round(meters)} / ${Math.round(total)} m`;$('profile-pointer').style.left=`${total?meters/total*100:0}%`;if(covered)scene?.setDistance(meters);const point=pointAtDistance(track,meters).point;const elevation=covered?terrainElevation(terrain,point.lat,point.lon):point.elevation;$('current-label').textContent=(meters===0?'スタート地点':meters>=total?'ゴール地点':`${(meters/1000).toFixed(2)} km 地点`)+(elevation===undefined?'':` · ${Math.round(elevation)} m`);}
function profile(){const samples=Array.from({length:121},(_,i)=>pointAtDistance(track,total*i/120).point);const values=samples.map(p=>covered?terrainElevation(terrain,p.lat,p.lon):p.elevation);const finite=values.filter((v):v is number=>v!==undefined&&Number.isFinite(v));const svg=$('profile');svg.replaceChildren();if(!finite.length){$('profile-min').textContent='標高データなし';$('profile-max').textContent='';return;}const lo=Math.min(...finite),hi=Math.max(...finite),span=Math.max(10,hi-lo);let path='',area='';values.forEach((v,i)=>{if(v===undefined){path+=' ';return;}path+=`${i===0||values[i-1]===undefined?'M':'L'}${i*5},${52-(v-lo)/span*44} `;});area=`M0,57 ${path} L600,57 Z`;for(const [d,fill,stroke] of [[area,'#dce7cf','none'],[path,'none','#9bb48c']]){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('fill',fill);p.setAttribute('stroke',stroke);p.setAttribute('stroke-width','1.5');svg.append(p);}$('profile-min').textContent=`標高 ${Math.round(lo)} m`;$('profile-max').textContent=`${Math.round(hi)} m`;$('profile-source').textContent=covered?'実DEMから計算 · 縦軸は見やすさのため拡大':'GPXに記録された標高';}
function applyTrack(next:Track,isSample=false){stop();track=next;covered=isCovered(track,terrain);const stats=routeStats(enriched(track));total=stats.distance;$('route-name').textContent=isSample?'須磨の、小さな縦走。':track.name;$('route-kind').textContent=isSample?'FIELD NOTE · SUMA, KOBE':'YOUR LOCAL TRAIL';$('route-subtitle').textContent=isSample?'栂尾山 → 横尾山 → 馬の背 → 東山':`${stats.pointCount.toLocaleString()} 点 · ${stats.segmentCount} 区間`;$('distance').textContent=(total/1000).toFixed(2);$('ascent').textContent=stats.gain===undefined?'—':String(Math.round(stats.gain));$('highest').textContent=stats.maxElevation===undefined?'—':String(Math.round(stats.maxElevation));$('coverage').hidden=covered;($('play') as HTMLButtonElement).disabled=!covered;document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.disabled=!covered);if(covered){scene.setScenery(scenery);scene.setTerrain(terrain);scene.setTrack(track);scene.setPeaks(peaks);scene.setPhotos(photos);scene.setMode(mode);$('terrain-label').textContent=terrain.name;$('terrain-meta').textContent=`${terrain.cols} × ${terrain.rows} DEM / ACTUAL SCALE 1:1`;}setPosition(0);profile();updateDetailUI();}
function updatePhotos(){const list=$('photos');list.replaceChildren();if(!photos.length){const e=document.createElement('span');e.className='empty-photos';e.textContent='スライダーで場所を選んで、写真を残せます。';list.append(e);}for(const p of photos){const b=document.createElement('button');b.className='photo-thumb';b.title=p.name;b.setAttribute('aria-label',`写真: ${p.name}`);const img=document.createElement('img');img.src=p.url;img.alt=p.name;b.append(img);b.onclick=()=>showPhoto(p.id);list.append(b);}$('photo-count').textContent=String(photos.length);scene?.setPhotos(photos);}
function showPhoto(id:string){const p=photos.find(p=>p.id===id);if(!p)return;stop();selectedPhoto=id;setPosition(p.distance);$('photo-title').textContent=p.name;($('photo-view') as HTMLImageElement).src=p.url;($('photo-dialog') as HTMLDialogElement).showModal();}
function project():Project{if(!covered)throw new Error('先にこのルートを覆う地形を読み込んでください。');return {version:1,track,terrain,photos,peaks,...(scenery?{scenery}: {})};}
async function sample(){const version=++loadVersion;controller?.abort();stop();const [d,g,p,f]=await Promise.all([fetch('./data/terrain.json').then(r=>r.json()),fetch('./data/sample-route.gpx').then(r=>r.text()),fetch('./data/sample-peaks.json').then(r=>r.json()),fetch('./data/sample-features.json').then(r=>r.json())]);if(version!==loadVersion)return;terrain=validateTerrain(d);scenery=validateScenery(f);peaks=p;photos=[];applyTrack(parseGPX(g),true);updatePhotos();dirty=false;}
async function changeFile(id:string,callback:(file:File)=>Promise<void>){const input=$(id) as HTMLInputElement;input.onchange=async()=>{const f=input.files?.[0];if(!f)return;stop();try{await callback(f);}catch(e){notify(e instanceof Error?e.message:'ファイルを読み込めませんでした。',true);}finally{input.value='';}};}
function preservePrompt(){return !dirty||confirm('まだ保存していない記録があります。現在のGPX・写真を置き換えますか？');}
$('dismiss').onclick=()=>$('notice').hidden=true;$('about').onclick=()=>($('about-dialog') as HTMLDialogElement).showModal();$('save').onclick=()=>($('export-dialog') as HTMLDialogElement).showModal();document.querySelectorAll<HTMLButtonElement>('[data-close]').forEach(b=>b.onclick=()=>($(b.dataset.close!) as HTMLDialogElement).close());
for(const [button,input] of [['import-gpx','gpx-file'],['open-project','project-file'],['import-terrain','terrain-file'],['coverage-terrain','terrain-file'],['add-photo','photo-file']])$(button).onclick=()=>$(input).click();
$('sample').onclick=async()=>{if(preservePrompt())try{await sample();}catch(e){notify(String(e),true);}};
changeFile('gpx-file',async f=>{if(f.size>10*1024*1024)throw new Error('GPXは10 MB以下にしてください。');const next=parseGPX(await f.text());if(!preservePrompt())return;loadVersion++;controller?.abort();photos=[];peaks=[];scenery=undefined;applyTrack(next);updatePhotos();dirty=true;notify(covered?'GPXを読み込みました。写真を置く場所をスライダーで選べます。':'GPXを読み込みました。3D表示には、このルートを覆う地形が必要です。');});
changeFile('project-file',async f=>{if(f.size>MAX_PROJECT_BYTES)throw new Error('プロジェクトは40 MB以下にしてください。');const p=readProject(await f.text());if(!isCovered(p.track,p.terrain))throw new Error('プロジェクトの地形がルート全体を覆っていません。');if(!preservePrompt())return;loadVersion++;controller?.abort();terrain=p.terrain;photos=p.photos;peaks=p.peaks;scenery=p.scenery;applyTrack(p.track);updatePhotos();dirty=false;notify('保存した記録を開きました。');});
changeFile('terrain-file',async f=>{if(f.size>20*1024*1024)throw new Error('地形JSONは20 MB以下にしてください。');const next=validateTerrain(JSON.parse(await f.text()));if(!isCovered(track,next))throw new Error('地形がルート全体を覆っていません。現在の地形は変更していません。');loadVersion++;controller?.abort();terrain=next;peaks=[];scenery=undefined;applyTrack(track);dirty=true;notify('実地形を読み込みました。');});
($('photo-file') as HTMLInputElement).onchange=async()=>{const input=$('photo-file') as HTMLInputElement;const files=Array.from(input.files??[]);const version=loadVersion;const distance=meters;const point=pointAtDistance(track,meters).point;try{if(photos.length+files.length>20)throw new Error('写真は20枚まで追加できます。');const pending:Photo[]=[];for(const f of files){const url=await importPhoto(f);pending.push({id:crypto.randomUUID(),name:f.name.slice(0,200),url,lat:point.lat,lon:point.lon,distance});}if(version!==loadVersion)return;photos.push(...pending);updatePhotos();dirty=true;notify(`${pending.length}枚の写真を ${Math.round(distance)} m 地点に追加しました。`);}catch(e){notify(String(e),true);}finally{input.value='';}};
$('remove-photo').onclick=()=>{photos=photos.filter(p=>p.id!==selectedPhoto);updatePhotos();dirty=true;($('photo-dialog') as HTMLDialogElement).close();};
$('save-project').onclick=()=>{try{download(new Blob([JSON.stringify(project())],{type:'application/json'}),'3d-yama-project.json');dirty=false;notify('プロジェクトの保存を開始しました。');}catch(e){notify(String(e),true);}};
$('save-viewer').onclick=async()=>{const b=$('save-viewer') as HTMLButtonElement;b.disabled=true;try{await exportViewer(project());dirty=false;notify('ビューアーZIPの保存を開始しました。');}catch(e){notify(String(e),true);}finally{b.disabled=false;}};
for(const id of ['load-gsi','coverage-gsi'])$(id).onclick=()=>($('gsi-dialog') as HTMLDialogElement).showModal();
$('confirm-gsi').onclick=async()=>{($('gsi-dialog') as HTMLDialogElement).close();controller?.abort();controller=new AbortController();const version=++loadVersion;const current=track;stop();notify('国土地理院の標高を取得しています…');try{const next=await fetchGsiTerrain(current,controller.signal);if(version!==loadVersion)return;terrain=next;peaks=[];scenery=undefined;applyTrack(current);dirty=true;notify('実標高を読み込みました。保存すると次回は通信なしで開けます。');}catch(e){if(version===loadVersion)notify(e instanceof Error?e.message:String(e),true);}};
document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode as typeof mode;scene.setMode(mode);document.querySelectorAll('[data-mode]').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});$('stage-help').textContent=mode==='walk'?'スライダー・再生でルートを歩く · ジオラマで全体へ戻る':mode==='overhead'?'北が上 · ホイールでズーム · ドラッグで移動':'ドラッグで回転 · ホイールでズーム · 右ドラッグで移動';});
$('reset').onclick=()=>{stop();mode='orbit';scene.reset();setPosition(0);$('stage-help').textContent='ドラッグで回転 · ホイールでズーム · 右ドラッグで移動';document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>{const active=b.dataset.mode==='orbit';b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});};$('capture').onclick=()=>{try{const a=document.createElement('a');a.href=scene.capture();a.download='3d-yama.png';a.click();}catch{notify('画像を保存できませんでした。',true);}};
function updateDetailUI(){
  for(const id of ['quality','quality-sidebar'])($(id) as HTMLSelectElement).value=quality;
  document.querySelectorAll<HTMLButtonElement>('[data-quality]').forEach(b=>{const active=b.dataset.quality===quality;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
  const label=quality==='low'?'DEMのみ · 影なし / DPR上限1':quality==='standard'?'遠景の樹冠 · 岩・階段 / DPR上限1.5':'近くの枝葉へ自動切替 · 近景96本まで / DPR上限2';
  $('detail-status').textContent=scenery?`${QUALITY[quality].label} · ${label}`:'実DEMを表示中 · 詳細地物は須磨サンプル限定';
  document.querySelectorAll<HTMLButtonElement>('[data-focus]').forEach(b=>b.disabled=!scenery?.features.some(f=>f.kind===b.dataset.focus));
}
function selectQuality(value:Quality){quality=value;scene?.setQuality(value);updateDetailUI();}
for(const id of ['quality','quality-sidebar'])($(id) as HTMLSelectElement).onchange=()=>selectQuality(($(id) as HTMLSelectElement).value as Quality);
document.querySelectorAll<HTMLButtonElement>('[data-quality]').forEach(b=>b.onclick=()=>selectQuality(b.dataset.quality as Quality));
$('route-visible').onchange=()=>scene?.setRouteVisible(($('route-visible') as HTMLInputElement).checked);
function featureCenter(f:DetailFeature):Coordinate {const g=f.geometry;if(g.type==='Point')return g.coordinates;const points=g.type==='LineString'?g.coordinates:g.coordinates[0];if(g.type==='LineString'){const a=points[Math.floor((points.length-1)/2)],b=points[Math.ceil((points.length-1)/2)];return [(a[0]+b[0])/2,(a[1]+b[1])/2];}return [points.reduce((s,p)=>s+p[0],0)/points.length,points.reduce((s,p)=>s+p[1],0)/points.length];}
document.querySelectorAll<HTMLButtonElement>('[data-focus]').forEach(b=>b.onclick=()=>{const f=scenery?.features.find(f=>f.kind===b.dataset.focus);if(!f)return;stop();selectQuality('high');mode='orbit';document.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(el=>{const active=el.dataset.mode==='orbit';el.classList.toggle('active',active);el.setAttribute('aria-pressed',String(active));});const focusKey=b.dataset.focus==='bare_rock'?'ridge':b.dataset.focus==='steps'?'stairs':'forest';const focus=scenery?.features.find(x=>x.focusKey===focusKey)??f;const [lon,lat]=featureCenter(focus);scene.focus(lon,lat,f.kind==='steps'?55:f.kind==='forest'?85:110);($('route-visible') as HTMLInputElement).checked=false;scene.setRouteVisible(false);$('stage-help').textContent=`${f.name} · ドラッグで回転 / 樹木・岩肌・階段は近似表現`;$('feature-source').setAttribute('href',f.sourceUrl);if(innerWidth<=650)document.querySelector('.stage')?.scrollIntoView({behavior:'smooth',block:'start'});});
$('progress').oninput=()=>{stop();setPosition(Number(($('progress') as HTMLInputElement).value));};$('play').onclick=()=>{if(playing){stop();return;}if(meters>=total)setPosition(0);playing=true;lastFrame=performance.now();$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','再生を停止');};
$('mobile-panel').onclick=()=>$('sidebar').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target===document.body&&!document.querySelector('dialog[open]')){e.preventDefault();$('play').click();}});
function tick(t:number){if(playing&&track){const dt=Math.min(.1,(t-lastFrame)/1000);setPosition(meters+dt*Number(($('speed') as HTMLSelectElement).value));if(meters>=total)stop();}lastFrame=t;requestAnimationFrame(tick);}requestAnimationFrame(tick);
async function init(){try{scene=new TrailScene($('scene'),value=>{stop();setPosition(value);});scene.onPhotoSelect=showPhoto;scene.onDetailStatus=message=>{if(message.includes('読み込めません')){notify(message,true);$('detail-status').textContent=message;}else updateDetailUI();};const r=await fetch('./data/project.json');const text=await r.text();if(r.ok&&text.trim()!=='null'){const p=readProject(text);terrain=p.terrain;photos=p.photos;peaks=p.peaks;scenery=p.scenery;if(!isCovered(p.track,terrain))throw new Error('保存された地形の範囲外です。');applyTrack(p.track);updatePhotos();}else await sample();}catch(e){notify(`初期化できませんでした: ${e instanceof Error?e.message:String(e)}`,true);$('coverage').hidden=false;$('coverage').textContent='3D表示を開始できません。WebGL対応ブラウザをお試しください。';}finally{$('loading').hidden=true;}}
void init();

// Read-only diagnostic counters; no route coordinates or photo content are exposed.
Object.defineProperty(window,'yamaDiagnostics',{value:Object.freeze({snapshot:()=>scene?.snapshot()}),writable:false});
